# -*- coding: utf-8 -*-
"""phase1_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-MHjvI6Z4H9wdmD1qC-su6cs2PWE8W6

# Phase 1 – Transformer Implementations (DS-462 GenAI with LLM)

This notebook implements **three minimal transformer architectures from scratch** as required in Phase 1 of the project:

1. **Encoder-only Transformer** – Intent Classification  
2. **Decoder-only Transformer** – Tiny GPT-style Language Model  
3. **Encoder–Decoder Transformer** – Query + Snippet → Response Generation  

All models are trained on **toy datasets** to validate end-to-end pipelines, attention mechanisms, and masking behavior.

All transformer components were implemented from scratch using PyTorch,
without relying on high-level nn.Transformer abstractions.
"""

import os
print(os.getcwd())




os.makedirs("/content/drive/MyDrive/genai-project/transformers/data", exist_ok=True)

"""## Encoder-Only Transformer – Intent Classification

### Task
Classify customer support queries into predefined intents:
- return
- warranty
- shipping
- payment
- product usage

### Architecture Characteristics
- Uses **bidirectional self-attention**
- No causal masking is applied
- Final encoder output is pooled and passed to a classification head

### Why Encoder-Only?
Encoder-only transformers (e.g., BERT) are ideal for **understanding tasks** such as classification because they attend to the **entire input sequence simultaneously**.
"""

# Create intent training data
intent_data = [
    {"text": "I want to return an item I bought last week", "label": "returns"},
    {"text": "Can I return opened products?", "label": "returns"},
    {"text": "What is the return policy for electronics?", "label": "returns"},
    {"text": "How many days do I have to return a product?", "label": "returns"},

    {"text": "How long is the warranty on this phone?", "label": "warranty"},
    {"text": "Is accidental damage covered under warranty?", "label": "warranty"},
    {"text": "Does the warranty cover battery issues?", "label": "warranty"},
    {"text": "What warranty do I get with this laptop?", "label": "warranty"},

    {"text": "When will my order be shipped?", "label": "shipping"},
    {"text": "How long does shipping take?", "label": "shipping"},
    {"text": "Can I track my shipment online?", "label": "shipping"},
    {"text": "Do you offer international shipping?", "label": "shipping"},

    {"text": "How do I pay with a credit card?", "label": "payment"},
    {"text": "Can I pay using debit card?", "label": "payment"},
    {"text": "Does the store accept international cards?", "label": "payment"},
    {"text": "Are there any installment payment options?", "label": "payment"},

    {"text": "How to connect the device to wifi?", "label": "product_usage"},
    {"text": "My screen is flickering, what should I do?", "label": "product_usage"},
    {"text": "How do I reset the device to factory settings?", "label": "product_usage"},
    {"text": "The device is overheating during use", "label": "product_usage"}
]

# Write to file
with open("/content/drive/MyDrive/genai-project/transformers/data/intent_data.json", "w") as f:
    for item in intent_data:
        f.write(str(item) + "\n")

print("intent_data.json created successfully!")

with open("/content/drive/MyDrive/genai-project/transformers/data/intent_data.json") as f:
    for i, line in enumerate(f):
        if i < 5:
            print(line)

"""Load & Inspect the Data"""

import ast

data = []

with open("/content/drive/MyDrive/genai-project/transformers/data/intent_data.json", "r") as f:
    for line in f:
        data.append(ast.literal_eval(line))

print("Total examples:", len(data))
print("First example:", data[0])

"""Convert Labels to Numbers"""

labels = sorted(list(set(item["label"] for item in data)))
label2idx = {label: idx for idx, label in enumerate(labels)}
idx2label = {idx: label for label, idx in label2idx.items()}

print("Label mapping:", label2idx)

"""Build a Vocabulary (Text → Numbers)"""

from collections import Counter

counter = Counter()

for item in data:
    for word in item["text"].lower().split():
        counter[word] += 1

# Special tokens
vocab = {
    "<pad>": 0,
    "<unk>": 1
}

# Add words to vocab
for word, _ in counter.most_common():
    if word not in vocab:
        vocab[word] = len(vocab)

print("Vocab size:", len(vocab))

"""Convert Text to Token IDs"""

MAX_LEN = 16

def encode_text(text):
    tokens = []
    for word in text.lower().split():
        tokens.append(vocab.get(word, vocab["<unk>"]))

    # truncate
    tokens = tokens[:MAX_LEN]

    # pad
    while len(tokens) < MAX_LEN:
        tokens.append(vocab["<pad>"])

    return tokens

sample = data[0]["text"]
print("Text:", sample)
print("Encoded:", encode_text(sample))

"""Create Dataset & DataLoader"""

import torch
from torch.utils.data import Dataset, DataLoader
import random

class IntentDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        x = torch.tensor(encode_text(item["text"]), dtype=torch.long)
        y = torch.tensor(label2idx[item["label"]], dtype=torch.long)
        return x, y

# Shuffle and split
random.shuffle(data)
split = int(0.8 * len(data))
train_data = data[:split]
val_data = data[split:]

train_dataset = IntentDataset(train_data)
val_dataset = IntentDataset(val_data)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=4)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

"""Transformer Components"""

import math
import torch.nn as nn

"""Multi-Head Self-Attention"""

class MultiHeadSelfAttention(nn.Module):
    def __init__(self, d_model, n_heads):
        super().__init__()
        assert d_model % n_heads == 0

        self.d_model = d_model
        self.n_heads = n_heads
        self.d_head = d_model // n_heads

        self.q = nn.Linear(d_model, d_model)
        self.k = nn.Linear(d_model, d_model)
        self.v = nn.Linear(d_model, d_model)
        self.out = nn.Linear(d_model, d_model)

    def forward(self, x):
        B, T, D = x.shape

        Q = self.q(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)
        K = self.k(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)
        V = self.v(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_head)
        attn = torch.softmax(scores, dim=-1)

        context = torch.matmul(attn, V)
        context = context.transpose(1, 2).contiguous().view(B, T, D)

        return self.out(context)

"""Transformer Encoder Layer"""

class TransformerEncoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ff):
        super().__init__()

        self.attn = MultiHeadSelfAttention(d_model, n_heads)
        self.norm1 = nn.LayerNorm(d_model)

        self.ff = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x):
        x = self.norm1(x + self.attn(x))
        x = self.norm2(x + self.ff(x))
        return x

"""Encoder-Only Intent Classifier"""

class EncoderIntentClassifier(nn.Module):
    def __init__(self, vocab_size, num_classes,
                 d_model=64, n_heads=4, n_layers=2, max_len=16):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_embedding = nn.Parameter(torch.zeros(1, max_len, d_model))

        self.layers = nn.ModuleList([
            TransformerEncoderLayer(d_model, n_heads, d_model * 4)
            for _ in range(n_layers)
        ])

        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Linear(d_model, num_classes)

    def forward(self, x):
        x = self.embedding(x) + self.pos_embedding[:, :x.size(1), :]

        for layer in self.layers:
            x = layer(x)

        x = x.transpose(1, 2)
        x = self.pool(x).squeeze(-1)

        return self.fc(x)

"""Train the Model"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = EncoderIntentClassifier(
    vocab_size=len(vocab),
    num_classes=len(label2idx)
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

train_losses = []
val_accuracies = []

for epoch in range(15):
    model.train()
    total_loss = 0

    for x, y in train_loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    train_losses.append(avg_loss)

    # Validation
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(device), y.to(device)
            preds = model(x).argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    acc = correct / total
    val_accuracies.append(acc)

    print(f"Epoch {epoch+1} | Loss: {avg_loss:.4f} | Val Acc: {acc:.2f}")

"""Plot Loss Curve"""

import matplotlib.pyplot as plt

plt.plot(train_losses)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss - Encoder Intent Classifier")
plt.show()

"""### Sanity Check – Encoder-Only Intent Classifier

To verify that the encoder-only transformer has learned meaningful representations,
we run it on a few unseen customer queries and inspect the predicted intent labels.

"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -------- Sanity Check: Encoder-Only Intent Classifier (DEVICE SAFE) --------

model.eval()

test_queries = [
    "Can I return this product?",
    "How long is the warranty?",
    "Where is my order?",
    "How do I use this device?"
]

with torch.no_grad():
    for q in test_queries:
        token_ids = tokenize(q, vocab)
        x = torch.tensor(token_ids, dtype=torch.long).unsqueeze(0).to(device)

        logits = model(x)
        pred = logits.argmax(dim=1).item()

        print("Query:", q)
        print("Predicted Intent:", id2label[pred])
        print("-" * 40)

"""### Analysis of Intent Classification Results

The intent predictions are not perfectly accurate, which is expected due to:
- Extremely small toy training dataset
- Random initialization (no pretraining)
- Semantically overlapping intent classes
- Limited model capacity

The purpose of this experiment is to validate the **end-to-end transformer pipeline**
and not to achieve high classification accuracy.
Despite limited accuracy, the model demonstrates correct forward propagation,
pooling, and classification behavior.

"""

def predict_intent(text):
    model.eval()
    encoded = torch.tensor([encode_text(text)], dtype=torch.long).to(device)
    with torch.no_grad():
        logits = model(encoded)
        pred = logits.argmax(dim=1).item()
    return idx2label[pred]

tests = [
    "I want to return my phone",
    "Is this under warranty?",
    "How do I track shipping?",
    "How do I pay using card?",
    "My device is overheating"
]

for t in tests:
    print(t, "→", predict_intent(t))

"""## Decoder-Only Transformer – Tiny Language Model

### Task
Train a **GPT-style language model** on small FAQ-style text data to generate answers autoregressively.

### Architecture Characteristics
- Uses **causal (look-ahead) masking**
- Predicts the **next token** given previous tokens
- Trained using **shifted input-target pairs**

### Why Causal Masking?
Causal masking prevents the model from attending to **future tokens**, ensuring proper autoregressive generation.
Without it, the model would leak future information during training.

Prepare Text for Language Modeling
"""

# Prepare corpus for GPT (only text)
corpus = [item["text"].lower() for item in data]

print("Sample sentence:")
print(corpus[0])

"""Create Token Sequences for GPT"""

def make_gpt_data(sentence, max_len=16):
    tokens = [vocab.get(w, vocab["<unk>"]) for w in sentence.split()]

    inputs = tokens[:-1]
    targets = tokens[1:]

    # truncate
    inputs = inputs[:max_len]
    targets = targets[:max_len]

    # pad
    while len(inputs) < max_len:
        inputs.append(vocab["<pad>"])
        targets.append(vocab["<pad>"])

    return inputs, targets

inp, tgt = make_gpt_data(corpus[0])
print("Input:", inp)
print("Target:", tgt)

"""GPT Dataset & DataLoader"""

class GPTDataset(Dataset):
    def __init__(self, corpus):
        self.corpus = corpus

    def __len__(self):
        return len(self.corpus)

    def __getitem__(self, idx):
        x, y = make_gpt_data(self.corpus[idx])
        return (
            torch.tensor(x, dtype=torch.long),
            torch.tensor(y, dtype=torch.long)
        )

gpt_dataset = GPTDataset(corpus)
gpt_loader = DataLoader(gpt_dataset, batch_size=4, shuffle=True)

print("GPT samples:", len(gpt_dataset))

"""Masked Multi-Head Self-Attention"""

class MaskedMultiHeadSelfAttention(nn.Module):
    def __init__(self, d_model, n_heads):
        super().__init__()
        assert d_model % n_heads == 0

        self.n_heads = n_heads
        self.d_head = d_model // n_heads

        self.q = nn.Linear(d_model, d_model)
        self.k = nn.Linear(d_model, d_model)
        self.v = nn.Linear(d_model, d_model)
        self.out = nn.Linear(d_model, d_model)

    def forward(self, x):
        B, T, D = x.shape

        Q = self.q(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)
        K = self.k(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)
        V = self.v(x).view(B, T, self.n_heads, self.d_head).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_head)

        # causal mask
        mask = torch.tril(torch.ones(T, T)).to(x.device)
        scores = scores.masked_fill(mask == 0, float("-inf"))

        attn = torch.softmax(scores, dim=-1)
        context = torch.matmul(attn, V)

        context = context.transpose(1, 2).contiguous().view(B, T, D)
        return self.out(context)

"""GPT Decoder Block"""

class GPTBlock(nn.Module):
    def __init__(self, d_model, n_heads, d_ff):
        super().__init__()
        self.attn = MaskedMultiHeadSelfAttention(d_model, n_heads)
        self.norm1 = nn.LayerNorm(d_model)

        self.ff = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x):
        x = self.norm1(x + self.attn(x))
        x = self.norm2(x + self.ff(x))
        return x

"""Tiny GPT Model"""

class TinyGPT(nn.Module):
    def __init__(self, vocab_size, d_model=64, n_heads=4, n_layers=2, max_len=16):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_embedding = nn.Parameter(torch.zeros(1, max_len, d_model))

        self.blocks = nn.ModuleList([
            GPTBlock(d_model, n_heads, d_model * 4)
            for _ in range(n_layers)
        ])

        self.fc = nn.Linear(d_model, vocab_size)

    def forward(self, x):
        x = self.embedding(x) + self.pos_embedding[:, :x.size(1), :]

        for block in self.blocks:
            x = block(x)

        return self.fc(x)

"""Train GPT Model"""

gpt_model = TinyGPT(len(vocab)).to(device)
optimizer = torch.optim.Adam(gpt_model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(ignore_index=vocab["<pad>"])

gpt_losses = []

for epoch in range(20):
    gpt_model.train()
    total_loss = 0

    for x, y in gpt_loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        logits = gpt_model(x)
        loss = criterion(logits.view(-1, len(vocab)), y.view(-1))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(gpt_loader)
    gpt_losses.append(avg_loss)

    print(f"Epoch {epoch+1} | Loss: {avg_loss:.4f}")

"""Plot GPT Loss"""

plt.plot(gpt_losses)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss - Tiny GPT")
plt.show()

"""### Sanity Check – Decoder-Only Language Model

The decoder-only transformer is evaluated by generating text autoregressively
from short prompts. This verifies that causal masking and next-token prediction
are working correctly.

"""

# -------- Sanity Check: Decoder-Only Text Generation --------

model.eval()

prompts = [
    "return policy",
    "warranty period",
    "shipping time"
]

with torch.no_grad():
    for p in prompts:
        generated = generate_text(p, max_new_tokens=30)
        print("Prompt:", p)
        print("Generated:", generated)
        print("-" * 60)

"""### Analysis of Decoder-Only Generation Results

The decoder-only model generates text that combines fragments of multiple FAQ-style
questions seen during training. This behavior is expected due to:
- Training from scratch on a very small dataset
- Greedy decoding without temperature or top-k sampling
- Limited vocabulary, leading to `<unk>` tokens

Despite limited fluency and repetition, the model clearly demonstrates
correct autoregressive generation and causal masking, which is the primary
objective of this Phase-1 experiment.

Generate Text
"""

def generate_text(prompt, max_new_tokens=5):
    gpt_model.eval()

    tokens = [vocab.get(w, vocab["<unk>"]) for w in prompt.lower().split()]

    for _ in range(max_new_tokens):
        x = torch.tensor([tokens[-MAX_LEN:]], dtype=torch.long).to(device)
        with torch.no_grad():
            logits = gpt_model(x)

        next_token = logits[0, -1].argmax().item()
        tokens.append(next_token)

    # decode
    inv_vocab = {v: k for k, v in vocab.items()}
    return " ".join(inv_vocab[t] for t in tokens)

print(generate_text("i want to"))
print(generate_text("how do i"))

"""## Encoder–Decoder Transformer – Grounded Response Generation

### Task
Generate short agent-style responses given:
- A **customer query**
- A **retrieved policy or manual snippet**

This simulates **RAG-style generation** in a supervised setting.

### Inputs
**Encoder Input**:
- Query + supporting snippet

**Decoder Input**:
- Shifted target response (teacher forcing)

### Objective
Learn to generate **concise, grounded responses** based only on provided evidence.

QA Data
"""

qa_data = [
    ("what is the return policy", "you can return items within thirty days"),
    ("how many days for return", "return is allowed within thirty days"),
    ("can i return opened product", "opened products can be returned"),

    ("how long is the warranty", "warranty duration is one year"),
    ("does warranty cover battery", "battery is covered under warranty"),
    ("is accidental damage covered", "accidental damage is not covered"),

    ("how long does shipping take", "shipping usually takes five days"),
    ("do you offer international shipping", "yes international shipping is available"),
    ("can i track my shipment", "you can track shipment online"),

    ("how do i pay", "you can pay using credit card"),
    ("do you accept debit card", "yes debit card payment is accepted"),
    ("are installment options available", "installment options are available"),

    ("how to reset the device", "you can reset device from settings"),
    ("device is overheating", "please stop usage and contact support"),
    ("screen is flickering", "restart device or contact support"),

    ("how to connect wifi", "connect wifi from network settings"),
    ("how to update software", "software can be updated from settings"),
    ("device not turning on", "please charge device and try again")
]

print("QA pairs:", len(qa_data))

"""Encode Encoder Input & Decoder Output"""

def encode_seq(text, max_len=16):
    tokens = [vocab.get(w, vocab["<unk>"]) for w in text.split()]
    tokens = tokens[:max_len]
    while len(tokens) < max_len:
        tokens.append(vocab["<pad>"])
    return tokens

def make_seq2seq_pair(question, answer):
    enc = encode_seq(question)
    dec_in = encode_seq(answer)
    dec_out = dec_in[1:] + [vocab["<pad>"]]
    return enc, dec_in, dec_out

enc, din, dout = make_seq2seq_pair(*qa_data[0])
print(enc)
print(din)
print(dout)

"""Seq2Seq Dataset & Loader"""

class Seq2SeqDataset(Dataset):
    def __init__(self, qa_pairs):
        self.qa = qa_pairs

    def __len__(self):
        return len(self.qa)

    def __getitem__(self, idx):
        enc, din, dout = make_seq2seq_pair(*self.qa[idx])
        return (
            torch.tensor(enc),
            torch.tensor(din),
            torch.tensor(dout)
        )

seq_dataset = Seq2SeqDataset(qa_data)
seq_loader = DataLoader(seq_dataset, batch_size=2, shuffle=True)

"""Encoder Module"""

class TransformerEncoder(nn.Module):
    def __init__(self, vocab_size, d_model=64, n_heads=4, n_layers=2, max_len=16):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, d_model)
        self.pos = nn.Parameter(torch.zeros(1, max_len, d_model))
        self.layers = nn.ModuleList([
            TransformerEncoderLayer(d_model, n_heads, d_model * 4)
            for _ in range(n_layers)
        ])

    def forward(self, x):
        x = self.embed(x) + self.pos[:, :x.size(1), :]
        for layer in self.layers:
            x = layer(x)
        return x

"""Decoder Module (with cross-attention)"""

class TransformerDecoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ff):
        super().__init__()
        self.self_attn = MaskedMultiHeadSelfAttention(d_model, n_heads)
        self.cross_attn = CrossAttention(d_model, n_heads)

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)

        self.ff = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )

    def forward(self, x, enc_out):
        x = self.norm1(x + self.self_attn(x))
        x = self.norm2(x + self.cross_attn(x, enc_out))
        x = self.norm3(x + self.ff(x))
        return x

class CrossAttention(nn.Module):
    def __init__(self, d_model, n_heads):
        super().__init__()
        assert d_model % n_heads == 0

        self.n_heads = n_heads
        self.d_head = d_model // n_heads

        self.q = nn.Linear(d_model, d_model)
        self.k = nn.Linear(d_model, d_model)
        self.v = nn.Linear(d_model, d_model)
        self.out = nn.Linear(d_model, d_model)

    def forward(self, x, enc_out):
        # x: (B, dec_len, D)
        # enc_out: (B, enc_len, D)

        B, T_dec, D = x.shape
        T_enc = enc_out.size(1)

        Q = self.q(x).view(B, T_dec, self.n_heads, self.d_head).transpose(1, 2)
        K = self.k(enc_out).view(B, T_enc, self.n_heads, self.d_head).transpose(1, 2)
        V = self.v(enc_out).view(B, T_enc, self.n_heads, self.d_head).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_head)
        attn = torch.softmax(scores, dim=-1)

        context = torch.matmul(attn, V)
        context = context.transpose(1, 2).contiguous().view(B, T_dec, D)

        return self.out(context)

"""Full Encoder-Decoder Model"""

class Seq2SeqTransformer(nn.Module):
    def __init__(self, vocab_size, d_model=64, n_heads=4, n_layers=2, max_len=16):
        super().__init__()
        self.encoder = TransformerEncoder(vocab_size, d_model, n_heads, n_layers, max_len)
        self.decoder_embed = nn.Embedding(vocab_size, d_model)
        self.decoder_pos = nn.Parameter(torch.zeros(1, max_len, d_model))
        self.decoder_layers = nn.ModuleList([
            TransformerDecoderLayer(d_model, n_heads, d_model * 4)
            for _ in range(n_layers)
        ])
        self.fc = nn.Linear(d_model, vocab_size)

    def forward(self, enc_x, dec_x):
        enc_out = self.encoder(enc_x)
        x = self.decoder_embed(dec_x) + self.decoder_pos[:, :dec_x.size(1), :]
        for layer in self.decoder_layers:
            x = layer(x, enc_out)
        return self.fc(x)

"""Train Encoder-Decoder"""

seq2seq_losses = []   # ADD THIS LINE BEFORE THE LOOP

for epoch in range(40):
    seq_model.train()
    total_loss = 0

    for enc, din, dout in seq_loader:
        enc, din, dout = enc.to(device), din.to(device), dout.to(device)

        optimizer.zero_grad()
        logits = seq_model(enc, din)
        loss = criterion(logits.view(-1, len(vocab)), dout.view(-1))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(seq_loader)
    seq2seq_losses.append(avg_loss)   # STORE LOSS
    print(f"Epoch {epoch+1} | Loss: {avg_loss:.4f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.plot(seq2seq_losses, marker='o')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Encoder–Decoder Training Loss")
plt.grid(True)
plt.show()

"""### Encoder–Decoder Training Loss

The loss decreases over training epochs, indicating that the
encoder–decoder transformer successfully learns to map questions
to response sequences using teacher forcing. Minor fluctuations are
expected due to the small dataset size.

### Sanity Check – Encoder–Decoder Transformer

The encoder–decoder transformer is evaluated by generating short agent-style
responses conditioned on both a customer query and a supporting policy snippet.
This setup mimics the behavior required in a Retrieval-Augmented Generation (RAG) system.
"""

# ================= SANITY CHECK: ENCODER–DECODER TRANSFORMER =================

seq_model.eval()

# Example query + policy snippet
query = "Can I return after 30 days?"
snippet = "Returns are allowed within 15 days of purchase."

# Encode encoder input (query + snippet)
enc_tokens = encode_seq(query + " " + snippet)
enc_tokens = torch.tensor(enc_tokens, dtype=torch.long).unsqueeze(0).to(device)

# Decoder input: start token (<pad> is acceptable for Phase-1)
dec_tokens = torch.tensor([[vocab["<pad>"]]], dtype=torch.long).to(device)

with torch.no_grad():
    logits = seq_model(enc_tokens, dec_tokens)

print("Encoder input shape:", enc_tokens.shape)
print("Decoder input shape:", dec_tokens.shape)
print("Output logits shape:", logits.shape)

"""Generate Answer (Demo)"""

def answer_question(question, max_len=8):
    seq_model.eval()
    enc = torch.tensor([encode_seq(question)], dtype=torch.long).to(device)

    # start with a common word instead of <pad>
    dec = [vocab.get("you", vocab["<unk>"])]

    for _ in range(max_len):
        dec_tensor = torch.tensor([dec], dtype=torch.long).to(device)
        with torch.no_grad():
            logits = seq_model(enc, dec_tensor)
        next_token = logits[0, -1].argmax().item()
        if next_token == vocab["<pad>"]:
            break
        dec.append(next_token)

    return " ".join(idx2word[t] for t in dec)

idx2word = {v: k for k, v in vocab.items()}
print("idx2word created")

print(answer_question("how long is the warranty"))
print(answer_question("can i track my shipment"))
print(answer_question("how do i pay"))
print(answer_question("device is overheating"))

"""## Phase-1 Summary

In this phase, three transformer architectures were implemented from scratch:

- Encoder-only transformer for intent classification
- Decoder-only transformer for language modeling
- Encoder–decoder transformer for grounded response generation

Each model was trained on a small toy dataset and validated using loss curves
and sanity-check experiments. The implementations confirm correct attention
mechanisms, positional encoding, masking, and data flow, forming a strong
foundation for the Phase-2 RAG system.

"""